version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./app/sqlite_db:/app/sqlite_db
    environment:
      - DATABASE_URL=sqlite:////app/sqlite_db/tasks.db
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sqlite_data:
    driver: local